// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ABtn: typeof import('ant-design-vue/es')['Btn']
    AButton: typeof import('ant-design-vue/es')['Button']
    Src: typeof import('./src/components/Button/src/index.vue')['default']
  }
}

export { }
